variables=(
    LAB_DEFAULT_BACKGROUD_SCRIPT LAB_DEFAULT_CPUTIME LAB_DEFAULT_ENVIRONMENT
    LAB_DEFAULT_EXECUTOR LAB_DEFAULT_REQUIREMENTS LAB_DEFAULT_RETRY_COUNT
    LAB_DEFAULT_SLEEPTIME LAB_DEFAULT_TIMEOUT LAB_FAILOVER_ENABLED LAB_FAILOVER_HOME
    LAB_FAILOVER_HOST LAB_FAILOVER_PORT LAB_FAILOVER_RETRY LAB_MINORSTATUS_ENABLED
    LAB_PLUGIN_DB LAB_PLUGIN_EXECUTOR LAB_PLUGIN_LISTENER LAB_VO_DEFAULT_SE
    LAB_VO_NAME LAB_VO_USE_CLOSE_SE LAB_BOSH_CVMFS_PATH LAB_CONTAINERS_CVMFS_PATH
    LAB_UDOCKER_TAG LAB_MIN_AVG_DOWNLOAD_THROUGHPUT CONNECT_TIMEOUT BDII_TIMEOUT
    SRM_TIMEOUT SCRIPT_ROOT JDL_ROOT OUT_ROOT ERR_ROOT CACHE_DIR CACHE_FILE
    INVO_DIR OUT_EXT OUT_APP_EXT ERR_EXT ERR_APP_EXT ENV_EXECUTOR numberOfReplicas
)

# Loop through the variables and read their values from the configuration file
for variable in "${variables[@]}"; do
    value=$(jq -r ".gaswConstants.$variable" "$configurationJson")
    eval "$variable=\"$value\""
done


for variable in "${variables[@]}"; do
    echo "$variable: ${!variable}"
done